### ISSUE TITLE
Wayback Proxy not connecting to websites, "request_url" error and WinError 10061

### ISSUE THREAD

**Issue by thecinnsystem** [richardg867/WaybackProxy#23] opened 2023-11-05 02:31 UTC
So, as of today and possibly tonight, anytime I try to connect to a website it will immediately throw up a bunch of errors with the error "urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it", loading like 2 or 3 images before everything errors out. It's apparently also having errors with request_url. 

Update, heres the whole error.

[>] http://twitter.com/
[!] Failed to fetch Wayback availability data
[!] Fetch exception:
Traceback (most recent call last):
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1319, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1365, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1314, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1074, in _send_output
    self.send(msg)
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1018, in send
    self.connect()
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 984, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WaybackProxy-master\waybackproxy.py", line 197, in handle
    conn = urllib.request.urlopen(request_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1373, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theci\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by NTxC** [comment] 2023-11-11 17:45
Having the same exact issue.

**Comment by caiot5** [comment] 2023-11-12 10:24
Same thing here. I guess that the wayback machine is throttling the connections very hard. 
They might be under DDoS attacks.

**Comment by thecinnsystem** [comment] 2023-11-12 17:30
> Same thing here. I guess that the wayback machine is throttling the connections very hard. They might be under DDoS attacks.

That could be it tbh it’s been a lot slower downloading things off there too

**Comment by celguar** [comment] 2023-11-19 10:22
for example old WoW website
https://web.archive.org/web/20061201153414mp_/http://www.worldofwarcraft.com/info/
in my browser I can see all images and open it, in wayback proxy + 86box + win98 I can't see 95% images, proxy says winError 10061 when loading them. I tried quick images off and on

**Comment by celguar** [comment] 2023-11-19 10:24
Also half of the times I end up with Bad Gateway (fetch exception in proxy). Maybe proxy does not provide browser data or smth?

**Comment by celguar** [comment] 2023-11-19 11:43
btw for images that don't load if I open a second IE in win98 and paste image URL it loads just fine, just on page it doesn't

**Comment by celguar** [comment] 2023-11-19 23:49
I tried adding user agent to urllib.request.Request, tried setting timeout to 60. Still images and js files would mostly not load with error from topic name. While on my normal browser it opens without any issues. Anyone has ideas?

**Comment by thecinnsystem** [comment] 2023-11-19 23:52
> I tried adding user agent to urllib.request.Request, tried setting timeout to 60. Still images and js files would mostly not load with error from topic name. While on my normal browser it opens without any issues. Anyone has ideas?

Honestly no idea man, I’m hoping the devs do read this or smth bc the proxy is completely unusable in this state.

**Comment by JosephM101** [comment] 2023-12-12 01:45
Not sure if this has anything to do with it:

![image](https://github.com/richardg867/WaybackProxy/assets/28277730/3ce4ffa6-43e4-455d-8796-1801a9d86d99)

**Comment by thecinnsystem** [comment] 2023-12-12 01:48
> Not sure if this has anything to do with it:
> 
> ![image](https://private-user-images.githubusercontent.com/28277730/289719261-3ce4ffa6-43e4-455d-8796-1801a9d86d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDU5NDYsIm5iZiI6MTcwMjM0NTY0NiwicGF0aCI6Ii8yODI3NzczMC8yODk3MTkyNjEtM2NlNGZmYTYtNDNlNC00NTVkLTg3OTYtMTgwMWE5ZDg2ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NzEwNTRjZmEyYzNlOGIyM2I0MDU3MWExOWJiOGIzMmIwZjM2YmMzOTMzMDVmNmNmODEwNTJiNTFhYWYwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fO5fFthm9kWde10vmOUtJ32f1aAkBhQK6iZ1SLD-3Dg)

That wouldn’t make any sense, since it only started affecting me on 11/4/23. I could load as many websites as I pleased before that, now I can just barely get the basic HTML, unless it just throws up a bad gateway error.

**Comment by JuliusCruz2000** [comment] 2023-12-12 03:07
I also have the same problem. I think it has something to do with the Internet Archive servers

**Comment by caiot5** [comment] 2023-12-12 03:42
Looks like everyone is having the exact same issue. Would it be doable to code something to delay the requests for each individual file? I guess it would be the only workaround I can imagine so far while the Internet Archive is behaving this way.

**Comment by richardg867** [comment] 2023-12-19 14:56
I've managed to reproduce this issue myself. The Internet Archive must have deployed a firewall which doesn't like the constant opening and closing of connections performed by WaybackProxy's simple nature. I'm looking into fixing this by migrating to a better HTTP library capable of keep-alive, but this unfortunately means WaybackProxy will no longer be free of external dependencies.

**Comment by celguar** [comment] 2023-12-19 15:38
it already requires lru-dict, that is not in default Python 3, so I guess not a problem :)

**Comment by richardg867** [comment] 2023-12-19 20:15
The code now uses `urllib3` with a hard connection cap, which is enough to avoid hitting the firewall, and keep-alive brings a somewhat visible performance improvement as a bonus.

The `lru-dict` used here is a different one which is implemented locally, but now that dependencies are a thing, I might look into using an external one instead.

**Closed by richardg867** 2023-12-19 20:15 UTC

**Comment by 03stevensmi** [comment] 2023-12-19 21:01
@richardg867 yes! Definitely use external dependencies! It will provide us with a better experience and lots of new features/improvements. I seccond this! :)

**Comment by celguar** [comment] 2023-12-19 21:28
Well for me proxy didn't start after loading Python 3 basic version until I used pip to get lru dict

**Comment by celguar** [comment] 2023-12-20 11:03
urllib3 seems to fail with same errors
`[!] Fetch retries exceeded: <urllib3.connection.HTTPSConnection object at 0x0000023F52E14790>: Failed to establish a new connection: [WinError 10061]`

**Comment by caiot5** [comment] 2023-12-20 11:16
I still think you'll have to do something to delay the requests because I think it's not an AI-firewall but instead, a connection throttle.
You can trigger it even by surfing through pages using the regular wayback machine though, however it doesn't tell you directly, you simply will see that it doesn't load some images and stuff, but if you're patient enough and wait some minutes and reload the images (not the entire page), you'll be able to fetch them.

**Comment by richardg867** [comment] 2023-12-20 19:12
I also had the dangling connection issue with IE 5 on 86Box, but failed to diagnose it; it could be related to 86Box for all I know, as the data appears to be fully loaded and the TCP connection left half-closed until IE is explicitly told to stop loading.

Another potential mitigation for the connection issue is QUICK_IMAGES, which was apparently not working at all and I just pushed a fix. If your browser can do keep-alive, use the PAC file and respect the QUICK_IMAGES exception (IE 5/6 meet all these criteria, but Firefox 52 fails the latter), the issue is hit far less often in my brief testing.

Reducing the code's connection limit (the `PoolManager` `maxsize=`) to a smaller number like 1 is also an option, but it runs the risk of stuck loads or file downloads just hanging up the whole proxy.
