### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BenTop123** [richardg867/WaybackProxy#21] opened 2023-09-11 10:43 UTC
Wops! Error opening config.json
Traceback (most recent call last):
  File "c:\Users\User\Downloads\WaybackProxy-master\WaybackProxy-master\waybackproxy.py", line 26, in <module>
    shared_state = SharedState()
                   ^^^^^^^^^^^^^
  File "c:\Users\User\Downloads\WaybackProxy-master\WaybackProxy-master\waybackproxy.py", line 17, in __init__
    self.availability_cache = lrudict.LRUDict(maxduration=86400, maxsize=1024) if WAYBACK_API else None
                                                                                  ^^^^^^^^^^^
NameError: name 'WAYBACK_API' is not defined

**Comment by mba08mc** [comment] 2023-09-28 13:53
same issue here

**Comment by 03stevensmi** [comment] 2023-10-24 08:08
@richardg867 anything?

**Comment by mba08mc** [comment] 2023-10-24 09:26
Yh, on mac instead of launching using terminal and typing python3 waybackproxy.py. Instead, install xcode and then when it has installed. Right click on waybackproxy.py and select open woth and you should see python launcher there. It works using python launcher

**Comment by richardg867** [comment] 2023-10-27 14:19
Probably a Python version issue or config.json being missing. I'm closing this as can't reproduce, but if this issue can be reproduced with the latest commit which should have more descriptive error messages, feel free to reopen.

**Closed by richardg867** 2023-10-27 14:19 UTC
